# type Task
#   @model
#   @auth(
#     rules: [
#       { allow: groups, groups: ["Managers"], queries: null, mutations: [create, update, delete] }
#       { allow: groups, groups: ["Employees"], queries: [get, list], mutations: null }
#     ]
#   ) {
#   id: ID!
#   title: String!
#   description: String
#   status: String
# }
# type PrivateNote @model @auth(rules: [{ allow: owner }]) {
#   id: ID!
#   content: String!
# }

enum HighlightType {
  Annotation
  Highlight
}

enum DeviceType {
  Kindle
  Kobo
  Pdf
  Epub
  Web
}

type Highlight @model @auth(rules: [{ allow: owner }]) {
  # @key(
  #   name: "byDueDate"
  #   fields: ["homeworkStudentId", "dueDate"]
  #   queryField: "homeworkByDueDate"
  # )
  # -----------\ userid -------------------\ text hash
  # 613e5539-1ab7-4624-9b2e-b91d2e8816a8:LTc4NjYwMDA5NQ==
  id: ID!
  type: HighlightType!
  deviceType: DeviceType!
  title: String!
  isbn: String
  author: String
  page: Int
  startOffset: Int
  endOffset: Int
  text: String
  annotation: String
  annotationExtra: String
  date: String
  uri: String
}

type Document @model @auth(rules: [{ allow: owner }]) {
  # -----------\ userid -------------------\ fileName hash
  # 613e5539-1ab7-4624-9b2e-b91d2e8816a8:LTc4NjYwMDA5NQ==
  id: ID!
  library: String!
  name: String!
  fileName: String!
  type: DeviceType
}
